
1. Login.mmd
2. Register.mmd
3. GetDetailItem.mmd
4. GetStoreInfo.mmd
5. GetRecomendItem.mmd
6. AddItemToCart.mmd
7. ManageCart.mmd
8. Checkout.mmd
9. ReceiveOrder.mmd
10. GetUserOrders.mmd
11. CreateReview.mmd
12. GetUserReviews.mmd
13. CreateStore.mmd
14. GetStoreProducts.mmd
15. CreateStoreProduct.mmd
16. GetStoreEtalase.mmd
17. CreateStoreEtalase.mmd
18. EditStoreEtalase.mmd
19. DeleteStoreEtalase.mmd
20. GetStoreOrders.mmd
21. AcceptStoreOrders.mmd
22. ShipStoreOrders.mmd
23. CancelStoreOrders.mmd
24. GetStoreDetail.mmd
25. EditStoreInfo.mmd
26. GetAdminCategory.mmd
27. CreateAdminCategory.mmd
28. EditAdminCategory.mmd
29. GetAdminVariantType.mmd
30. CreateAdminVariantType.mmd
31. GetAdminStores.mmd
32. AdminApproveStore.mmd
33. AdminRejectStore.mmd