%%{init: {'theme': 'base', 'themeVariables': { 'fontSize': '13px', 'fontFamily': 'Inter'}}}%%
sequenceDiagram
  actor Admin
  participant V_ASP as View #10095; AdminStorePage
  participant P_AS as Pop-up #10095; ApproveStore
  participant C_S as Controller #10095; StoreController
  participant M_S as Model #10095; Store

  Admin->>V_ASP: klik tombol "Setujui" di salah satu data
  
  activate Admin

  activate V_ASP

  V_ASP->>P_AS: setIsModalApproveOpen(true)

  activate P_AS

  Admin->>P_AS: klik tombl "Setujui"
  P_AS->>C_S: update_store_status()

  activate C_S

  C_S->>M_S: update()
  
  activate M_S
  
  M_S-->>C_S: return

  deactivate M_S

  C_S-->>V_ASP: return view

  deactivate C_S
  
  V_ASP->>P_AS: setIsModalApproveOpen(false)

  deactivate P_AS
  deactivate V_ASP
  
  deactivate Admin