%%{init: {'theme': 'base', 'themeVariables': { 'fontSize': '13px', 'fontFamily': 'Inter'}}}%%
sequenceDiagram
  actor Penjual
  participant V_CP as View #10095; CreateProductPage
  participant C_P as Controller #10095; ProductController
  participant M_P as Model #10095; Product
  participant V_SP as View #10095; SellerProductPage


  Penjual->>V_CP: Klik tombol "Submit" di halaman tambah produk
  activate Penjual

  activate V_CP

  V_CP->>C_P: store()

  deactivate V_CP

  activate C_P

  opt Invalid Input
    C_P-->>Penjual: return validation message
  end

  C_P->>M_P: create()

  activate M_P

  M_P-->>C_P: data produk

  deactivate M_P

  activate V_SP
  C_P-->>V_SP: return view with data
  deactivate V_SP

  deactivate C_P
  deactivate Penjual